sudo: required
language: python
services:
- docker
script:
- make test
deploy:
  provider: script
  on:
    branch: master
  script: DOCKER_USERNAME=$DOCKER_USERNAME DOCKER_PASSWORD=$DOCKER_PASSWORD bash .travis/docker_push

